[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[build]
publish = "dist/"
command = "rustup toolchain install nightly && rustup target add wasm32-unknown-unknown && cargo install --locked trunk && trunk build --release"